Draft: Add dragonflight support
HarielMods/RaidSkipper pull request #2
Opened 2023-05-06 12:56 UTC by Skylli202

Hi,

Did not wait your answer to make a MR as I liked the exercise (never coded a wow addon). Feel free to reject it if you do not want any contribution.

This is only a draft, as the following items need to be taken care of:
- Both VOTI and Aberrus `instanceId` are wrong. Could not find what was the ID that you used on the other instance. Only found `zoneId` on wowhead, but did not match with the one you had for previous raid.
- Aberrus seems to only have two skip quests (the normal skip seems to be unavailable) [source](https://www.wowhead.com/quests/raids/aberrus-the-shadowed-crucible), I have no clue on much it can break the rest of the addon. You seems to use `key,`

> PS: I am sorry about auto format on save who edited some line who does not relate to this MR.

2023-06-11 02:53 UTC, HarielMods requested changes
Change those instanceIds and I'll get this PR approved!

2023-06-11 02:53 UTC, HarielMods commented on Data.lua
> +            { name = "Aberrus, the Shadowed Crucible", instanceId = 2296, mythicId = 76086, heroicId = 76085 },
ATSC instaceId is 14663

2023-06-11 02:53 UTC, HarielMods commented on Data.lua
>              { name = "Vault of the Incarnates", instanceId = 2296, mythicId = 71020, heroicId = 71019, normalId = 71018 },
VOTI instanceId is 14030

2023-06-12 16:15 UTC, Skylli202 commented on Data.lua
> +            { name = "Aberrus, the Shadowed Crucible", instanceId = 2296, mythicId = 76086, heroicId = 76085 },
Correction done

2023-06-12 16:15 UTC, Skylli202 commented on Data.lua
>              { name = "Vault of the Incarnates", instanceId = 2296, mythicId = 71020, heroicId = 71019, normalId = 71018 },
Correction done

2023-06-13 14:43 UTC, BS5 commented
Adding this pull request!

2023-06-13 14:43 UTC, merged